---
sources:
  local:
    - atom.yml
    #- sublime3.yml
    - evernote.yml  # looks like this doesn't like the TOS screen on the .dmg from Evernote
    - skitch.yml
    - calibre.yml
    #- hipchat.yml
    - send-to-kindle.yml
    - tmux.yml
    #- scala-ide.yml

  git:
    - name: 'osx'
      repo: 'https://github.com/jayshao/ansible-osx'
      playbooks:
         - homebrew.yml
         - chrome-beta.yml
         - dropbox.yml
         - github.yml
         - gitx.yml
         - intellij-idea-ultimate.yml
         - iterm2.yml
         - java7.yml
         - skype.yml
         - spotify.yml
         - vagrant.yml
         - virtualbox.yml
