---
sources:
  local:
    - sublime3.yml
    - evernote.yml  # looks like this doesn't like the TOS screen on the .dmg from Evernote
    - skitch.yml
    - calibre.yml
    # hipchat.yml
    - send-to-kindle.yml
    - tmux.yml
    # scala-ide.yml

  git:
    - name: 'osx'
      repo: 'https://github.com/jayshao/ansible-osx'
      playbooks:
         - homebrew.yml
         #- adium.yml
         #- alfred.yml
         # better-touch-tool.yml
         - chrome-beta.yml
         - dropbox.yml
         - github.yml
         - gitx.yml
         - intellij-idea-ultimate.yml
         - iterm2.yml
         - java7.yml
         #- libreoffice.yml
         #- sequel-pro.yml
         - skype.yml
         #- truecrypt.yml
         #- usb-overdrive.yml
         - vagrant.yml
         - virtualbox.yml
         #- xtra-finder.yml
