---
- hosts: workstation

  tasks:
    - name: install HipChat
      mac_pkg: pkg_type=app
               url=https://www.hipchat.com/downloads/latest/mac
               archive_type=zip archive_path="HipChat.app"
      sudo: yes