---
- hosts: workstation

  tasks:
    - name: install Sublime Text 3 
      mac_pkg: pkg_type=app pkg_version=3047a
               url=http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%20Build%203047.dmg
               archive_type=dmg archive_path="Sublime Text.app"
      sudo: yes
    - name: Create symlink subl for Sublime Text's subl command
      file: src=/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl dest=/usr/bin/subl state=link
    - name: Create symlink sublime for Sublime Text's subl command
      file: src=/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl dest=/usr/bin/sublime state=link
