---
- hosts: workstation

  tasks:
    - name: install Sublime Text 3
      homebrew_cask: name=sublime-text3 state=absent
      sudo: yes
    #- name: Create symlink subl for Sublime Text's subl command
    #    file: src=/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl dest=/usr/bin/subl state=link
    #- name: Create symlink sublime for Sublime Text's subl command
    #  file: src=/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl dest=/usr/bin/sublime state=link
