---
- hosts: workstation

  tasks:
    - name: install Sublime Text 3 
      mac_pkg: pkg_type=app pkg_version=3047
               url=http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%20Build%203047.dmg
               archive_type=dmg archive_path="Sublime Text.app"
      sudo: yes

