---
- hosts: workstation

  tasks:
    - name: install tilemill
      mac_pkg: pkg_type=app
               url=http://tilemill.s3.amazonaws.com/latest/TileMill-0.10.1.zip
               archive_type=zip archive_path="TileMill.app"
      sudo: yes